package elaborate.editor.model;

import org.assertj.core.api.AbstractAssert;
// Assertions is needed if an assertion for Iterable is generated
import org.assertj.core.api.Assertions;
import elaborate.editor.model.orm.User;
import java.util.Date;


/**
 * {@link AbstractDocument} specific assertions - Generated by CustomAssertionGenerator.
 */
public class AbstractDocumentAssert extends AbstractAssert<AbstractDocumentAssert, AbstractDocument> {

  /**
   * Creates a new </code>{@link AbstractDocumentAssert}</code> to make assertions on actual AbstractDocument.
   * @param actual the AbstractDocument we want to make assertions on.
   */
  public AbstractDocumentAssert(AbstractDocument actual) {
    super(actual, AbstractDocumentAssert.class);
  }

  /**
   * An entry point for AbstractDocumentAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one's can write directly : <code>assertThat(myAbstractDocument)</code> and get specific assertion with code completion.
   * @param actual the AbstractDocument we want to make assertions on.
   * @return a new </code>{@link AbstractDocumentAssert}</code>
   */
  public static AbstractDocumentAssert assertThat(AbstractDocument actual) {
    return new AbstractDocumentAssert(actual);
  }

  /**
   * Verifies that the actual AbstractDocument's createdOn is equal to the given one.
   * @param createdOn the given createdOn to compare the actual AbstractDocument's createdOn to.
   * @return this assertion object.
   * @throws AssertionError - if the actual AbstractDocument's createdOn is not equal to the given one.
   */
  public AbstractDocumentAssert hasCreatedOn(Date createdOn) {
    // check that actual AbstractDocument we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String errorMessage = "\nExpected createdOn of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // null safe check
    Date actualCreatedOn = actual.getCreatedOn();
    if (!org.assertj.core.util.Objects.areEqual(actualCreatedOn, createdOn)) {
      failWithMessage(errorMessage, actual, createdOn, actualCreatedOn);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual AbstractDocument's creator is equal to the given one.
   * @param creator the given creator to compare the actual AbstractDocument's creator to.
   * @return this assertion object.
   * @throws AssertionError - if the actual AbstractDocument's creator is not equal to the given one.
   */
  public AbstractDocumentAssert hasCreator(User creator) {
    // check that actual AbstractDocument we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String errorMessage = "\nExpected creator of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // null safe check
    User actualCreator = actual.getCreator();
    if (!org.assertj.core.util.Objects.areEqual(actualCreator, creator)) {
      failWithMessage(errorMessage, actual, creator, actualCreator);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual AbstractDocument's id is equal to the given one.
   * @param id the given id to compare the actual AbstractDocument's id to.
   * @return this assertion object.
   * @throws AssertionError - if the actual AbstractDocument's id is not equal to the given one.
   */
  public AbstractDocumentAssert hasId(long id) {
    // check that actual AbstractDocument we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String errorMessage = "\nExpected id of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // check
    long actualId = actual.getId();
    if (actualId != id) {
      failWithMessage(errorMessage, actual, id, actualId);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual AbstractDocument's modifiedOn is equal to the given one.
   * @param modifiedOn the given modifiedOn to compare the actual AbstractDocument's modifiedOn to.
   * @return this assertion object.
   * @throws AssertionError - if the actual AbstractDocument's modifiedOn is not equal to the given one.
   */
  public AbstractDocumentAssert hasModifiedOn(Date modifiedOn) {
    // check that actual AbstractDocument we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String errorMessage = "\nExpected modifiedOn of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // null safe check
    Date actualModifiedOn = actual.getModifiedOn();
    if (!org.assertj.core.util.Objects.areEqual(actualModifiedOn, modifiedOn)) {
      failWithMessage(errorMessage, actual, modifiedOn, actualModifiedOn);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual AbstractDocument's modifier is equal to the given one.
   * @param modifier the given modifier to compare the actual AbstractDocument's modifier to.
   * @return this assertion object.
   * @throws AssertionError - if the actual AbstractDocument's modifier is not equal to the given one.
   */
  public AbstractDocumentAssert hasModifier(User modifier) {
    // check that actual AbstractDocument we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String errorMessage = "\nExpected modifier of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // null safe check
    User actualModifier = actual.getModifier();
    if (!org.assertj.core.util.Objects.areEqual(actualModifier, modifier)) {
      failWithMessage(errorMessage, actual, modifier, actualModifier);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual AbstractDocument's name is equal to the given one.
   * @param name the given name to compare the actual AbstractDocument's name to.
   * @return this assertion object.
   * @throws AssertionError - if the actual AbstractDocument's name is not equal to the given one.
   */
  public AbstractDocumentAssert hasName(String name) {
    // check that actual AbstractDocument we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String errorMessage = "\nExpected name of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // null safe check
    String actualName = actual.getName();
    if (!org.assertj.core.util.Objects.areEqual(actualName, name)) {
      failWithMessage(errorMessage, actual, name, actualName);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual AbstractDocument's rev is equal to the given one.
   * @param rev the given rev to compare the actual AbstractDocument's rev to.
   * @return this assertion object.
   * @throws AssertionError - if the actual AbstractDocument's rev is not equal to the given one.
   */
  public AbstractDocumentAssert hasRev(long rev) {
    // check that actual AbstractDocument we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String errorMessage = "\nExpected rev of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // check
    long actualRev = actual.getRev();
    if (actualRev != rev) {
      failWithMessage(errorMessage, actual, rev, actualRev);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual AbstractDocument's title is equal to the given one.
   * @param title the given title to compare the actual AbstractDocument's title to.
   * @return this assertion object.
   * @throws AssertionError - if the actual AbstractDocument's title is not equal to the given one.
   */
  public AbstractDocumentAssert hasTitle(String title) {
    // check that actual AbstractDocument we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String errorMessage = "\nExpected title of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // null safe check
    String actualTitle = actual.getTitle();
    if (!org.assertj.core.util.Objects.areEqual(actualTitle, title)) {
      failWithMessage(errorMessage, actual, title, actualTitle);
    }

    // return the current assertion for method chaining
    return this;
  }

}
