package elaborate.editor.model;

import org.assertj.core.api.AbstractAssert;
// Assertions is needed if an assertion for Iterable is generated
import org.assertj.core.api.Assertions;


/**
 * {@link FacetType} specific assertions - Generated by CustomAssertionGenerator.
 */
public class FacetTypeAssert extends AbstractAssert<FacetTypeAssert, FacetType> {

  /**
   * Creates a new </code>{@link FacetTypeAssert}</code> to make assertions on actual FacetType.
   * @param actual the FacetType we want to make assertions on.
   */
  public FacetTypeAssert(FacetType actual) {
    super(actual, FacetTypeAssert.class);
  }

  /**
   * An entry point for FacetTypeAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one's can write directly : <code>assertThat(myFacetType)</code> and get specific assertion with code completion.
   * @param actual the FacetType we want to make assertions on.
   * @return a new </code>{@link FacetTypeAssert}</code>
   */
  public static FacetTypeAssert assertThat(FacetType actual) {
    return new FacetTypeAssert(actual);
  }

  /**
   * Verifies that the actual FacetType's declaringClass is equal to the given one.
   * @param declaringClass the given declaringClass to compare the actual FacetType's declaringClass to.
   * @return this assertion object.
   * @throws AssertionError - if the actual FacetType's declaringClass is not equal to the given one.
   */
  public FacetTypeAssert hasDeclaringClass(Class declaringClass) {
    // check that actual FacetType we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String errorMessage = "\nExpected declaringClass of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // null safe check
    Class actualDeclaringClass = actual.getDeclaringClass();
    if (!org.assertj.core.util.Objects.areEqual(actualDeclaringClass, declaringClass)) {
      failWithMessage(errorMessage, actual, declaringClass, actualDeclaringClass);
    }

    // return the current assertion for method chaining
    return this;
  }

}
