package elaborate.editor.model;

import org.assertj.core.api.AbstractAssert;
// Assertions is needed if an assertion for Iterable is generated
import org.assertj.core.api.Assertions;


/**
 * {@link Sitemap} specific assertions - Generated by CustomAssertionGenerator.
 */
public class SitemapAssert extends AbstractAssert<SitemapAssert, Sitemap> {

  /**
   * Creates a new </code>{@link SitemapAssert}</code> to make assertions on actual Sitemap.
   * @param actual the Sitemap we want to make assertions on.
   */
  public SitemapAssert(Sitemap actual) {
    super(actual, SitemapAssert.class);
  }

  /**
   * An entry point for SitemapAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one's can write directly : <code>assertThat(mySitemap)</code> and get specific assertion with code completion.
   * @param actual the Sitemap we want to make assertions on.
   * @return a new </code>{@link SitemapAssert}</code>
   */
  public static SitemapAssert assertThat(Sitemap actual) {
    return new SitemapAssert(actual);
  }

}
