package elaborate.editor.model.orm;

import org.assertj.core.api.AbstractAssert;
// Assertions is needed if an assertion for Iterable is generated
import org.assertj.core.api.Assertions;
import java.util.Date;


/**
 * {@link ProjectMetadataItem} specific assertions - Generated by CustomAssertionGenerator.
 */
public class ProjectMetadataItemAssert extends AbstractAssert<ProjectMetadataItemAssert, ProjectMetadataItem> {

  /**
   * Creates a new </code>{@link ProjectMetadataItemAssert}</code> to make assertions on actual ProjectMetadataItem.
   * @param actual the ProjectMetadataItem we want to make assertions on.
   */
  public ProjectMetadataItemAssert(ProjectMetadataItem actual) {
    super(actual, ProjectMetadataItemAssert.class);
  }

  /**
   * An entry point for ProjectMetadataItemAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one's can write directly : <code>assertThat(myProjectMetadataItem)</code> and get specific assertion with code completion.
   * @param actual the ProjectMetadataItem we want to make assertions on.
   * @return a new </code>{@link ProjectMetadataItemAssert}</code>
   */
  public static ProjectMetadataItemAssert assertThat(ProjectMetadataItem actual) {
    return new ProjectMetadataItemAssert(actual);
  }

  /**
   * Verifies that the actual ProjectMetadataItem's createdOn is equal to the given one.
   * @param createdOn the given createdOn to compare the actual ProjectMetadataItem's createdOn to.
   * @return this assertion object.
   * @throws AssertionError - if the actual ProjectMetadataItem's createdOn is not equal to the given one.
   */
  public ProjectMetadataItemAssert hasCreatedOn(Date createdOn) {
    // check that actual ProjectMetadataItem we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String errorMessage = "\nExpected createdOn of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // null safe check
    Date actualCreatedOn = actual.getCreatedOn();
    if (!org.assertj.core.util.Objects.areEqual(actualCreatedOn, createdOn)) {
      failWithMessage(errorMessage, actual, createdOn, actualCreatedOn);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual ProjectMetadataItem's creator is equal to the given one.
   * @param creator the given creator to compare the actual ProjectMetadataItem's creator to.
   * @return this assertion object.
   * @throws AssertionError - if the actual ProjectMetadataItem's creator is not equal to the given one.
   */
  public ProjectMetadataItemAssert hasCreator(User creator) {
    // check that actual ProjectMetadataItem we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String errorMessage = "\nExpected creator of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // null safe check
    User actualCreator = actual.getCreator();
    if (!org.assertj.core.util.Objects.areEqual(actualCreator, creator)) {
      failWithMessage(errorMessage, actual, creator, actualCreator);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual ProjectMetadataItem's data is equal to the given one.
   * @param data the given data to compare the actual ProjectMetadataItem's data to.
   * @return this assertion object.
   * @throws AssertionError - if the actual ProjectMetadataItem's data is not equal to the given one.
   */
  public ProjectMetadataItemAssert hasData(String data) {
    // check that actual ProjectMetadataItem we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String errorMessage = "\nExpected data of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // null safe check
    String actualData = actual.getData();
    if (!org.assertj.core.util.Objects.areEqual(actualData, data)) {
      failWithMessage(errorMessage, actual, data, actualData);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual ProjectMetadataItem's field is equal to the given one.
   * @param field the given field to compare the actual ProjectMetadataItem's field to.
   * @return this assertion object.
   * @throws AssertionError - if the actual ProjectMetadataItem's field is not equal to the given one.
   */
  public ProjectMetadataItemAssert hasField(String field) {
    // check that actual ProjectMetadataItem we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String errorMessage = "\nExpected field of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // null safe check
    String actualField = actual.getField();
    if (!org.assertj.core.util.Objects.areEqual(actualField, field)) {
      failWithMessage(errorMessage, actual, field, actualField);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual ProjectMetadataItem's id is equal to the given one.
   * @param id the given id to compare the actual ProjectMetadataItem's id to.
   * @return this assertion object.
   * @throws AssertionError - if the actual ProjectMetadataItem's id is not equal to the given one.
   */
  public ProjectMetadataItemAssert hasId(long id) {
    // check that actual ProjectMetadataItem we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String errorMessage = "\nExpected id of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // check
    long actualId = actual.getId();
    if (actualId != id) {
      failWithMessage(errorMessage, actual, id, actualId);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual ProjectMetadataItem's modifiedOn is equal to the given one.
   * @param modifiedOn the given modifiedOn to compare the actual ProjectMetadataItem's modifiedOn to.
   * @return this assertion object.
   * @throws AssertionError - if the actual ProjectMetadataItem's modifiedOn is not equal to the given one.
   */
  public ProjectMetadataItemAssert hasModifiedOn(Date modifiedOn) {
    // check that actual ProjectMetadataItem we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String errorMessage = "\nExpected modifiedOn of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // null safe check
    Date actualModifiedOn = actual.getModifiedOn();
    if (!org.assertj.core.util.Objects.areEqual(actualModifiedOn, modifiedOn)) {
      failWithMessage(errorMessage, actual, modifiedOn, actualModifiedOn);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual ProjectMetadataItem's modifier is equal to the given one.
   * @param modifier the given modifier to compare the actual ProjectMetadataItem's modifier to.
   * @return this assertion object.
   * @throws AssertionError - if the actual ProjectMetadataItem's modifier is not equal to the given one.
   */
  public ProjectMetadataItemAssert hasModifier(User modifier) {
    // check that actual ProjectMetadataItem we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String errorMessage = "\nExpected modifier of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // null safe check
    User actualModifier = actual.getModifier();
    if (!org.assertj.core.util.Objects.areEqual(actualModifier, modifier)) {
      failWithMessage(errorMessage, actual, modifier, actualModifier);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual ProjectMetadataItem's project is equal to the given one.
   * @param project the given project to compare the actual ProjectMetadataItem's project to.
   * @return this assertion object.
   * @throws AssertionError - if the actual ProjectMetadataItem's project is not equal to the given one.
   */
  public ProjectMetadataItemAssert hasProject(Project project) {
    // check that actual ProjectMetadataItem we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String errorMessage = "\nExpected project of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // null safe check
    Project actualProject = actual.getProject();
    if (!org.assertj.core.util.Objects.areEqual(actualProject, project)) {
      failWithMessage(errorMessage, actual, project, actualProject);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual ProjectMetadataItem's rev is equal to the given one.
   * @param rev the given rev to compare the actual ProjectMetadataItem's rev to.
   * @return this assertion object.
   * @throws AssertionError - if the actual ProjectMetadataItem's rev is not equal to the given one.
   */
  public ProjectMetadataItemAssert hasRev(long rev) {
    // check that actual ProjectMetadataItem we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String errorMessage = "\nExpected rev of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // check
    long actualRev = actual.getRev();
    if (actualRev != rev) {
      failWithMessage(errorMessage, actual, rev, actualRev);
    }

    // return the current assertion for method chaining
    return this;
  }

}
