package elaborate.editor.model;

import java.util.Date;

import org.assertj.core.api.AbstractAssert;

import elaborate.editor.model.orm.User;

// Assertions is needed if an assertion for Iterable is generated

/**
 * {@link AbstractTrackedEntity} specific assertions - Generated by CustomAssertionGenerator.
 */
public class AbstractTrackedEntityAssert extends AbstractAssert<AbstractTrackedEntityAssert, AbstractTrackedEntity> {

  /**
   * Creates a new </code>{@link AbstractTrackedEntityAssert}</code> to make assertions on actual AbstractTrackedEntity.
   * @param actual the AbstractTrackedEntity we want to make assertions on.
   */
  public AbstractTrackedEntityAssert(AbstractTrackedEntity actual) {
    super(actual, AbstractTrackedEntityAssert.class);
  }

  /**
   * An entry point for AbstractTrackedEntityAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one's can write directly : <code>assertThat(myAbstractTrackedEntity)</code> and get specific assertion with code completion.
   * @param actual the AbstractTrackedEntity we want to make assertions on.
   * @return a new </code>{@link AbstractTrackedEntityAssert}</code>
   */
  public static AbstractTrackedEntityAssert assertThat(AbstractTrackedEntity actual) {
    return new AbstractTrackedEntityAssert(actual);
  }

  /**
   * Verifies that the actual AbstractTrackedEntity's createdOn is equal to the given one.
   * @param createdOn the given createdOn to compare the actual AbstractTrackedEntity's createdOn to.
   * @return this assertion object.
   * @throws AssertionError - if the actual AbstractTrackedEntity's createdOn is not equal to the given one.
   */
  public AbstractTrackedEntityAssert hasCreatedOn(Date createdOn) {
    // check that actual AbstractTrackedEntity we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String errorMessage = "\nExpected createdOn of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

    // null safe check
    Date actualCreatedOn = actual.getCreatedOn();
    if (!org.assertj.core.util.Objects.areEqual(actualCreatedOn, createdOn)) {
      failWithMessage(errorMessage, actual, createdOn, actualCreatedOn);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual AbstractTrackedEntity's creator is equal to the given one.
   * @param creator the given creator to compare the actual AbstractTrackedEntity's creator to.
   * @return this assertion object.
   * @throws AssertionError - if the actual AbstractTrackedEntity's creator is not equal to the given one.
   */
  public AbstractTrackedEntityAssert hasCreator(User creator) {
    // check that actual AbstractTrackedEntity we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String errorMessage = "\nExpected creator of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

    // null safe check
    User actualCreator = actual.getCreator();
    if (!org.assertj.core.util.Objects.areEqual(actualCreator, creator)) {
      failWithMessage(errorMessage, actual, creator, actualCreator);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual AbstractTrackedEntity's id is equal to the given one.
   * @param id the given id to compare the actual AbstractTrackedEntity's id to.
   * @return this assertion object.
   * @throws AssertionError - if the actual AbstractTrackedEntity's id is not equal to the given one.
   */
  public AbstractTrackedEntityAssert hasId(long id) {
    // check that actual AbstractTrackedEntity we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String errorMessage = "\nExpected id of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

    // check
    long actualId = actual.getId();
    if (actualId != id) {
      failWithMessage(errorMessage, actual, id, actualId);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual AbstractTrackedEntity's modifiedOn is equal to the given one.
   * @param modifiedOn the given modifiedOn to compare the actual AbstractTrackedEntity's modifiedOn to.
   * @return this assertion object.
   * @throws AssertionError - if the actual AbstractTrackedEntity's modifiedOn is not equal to the given one.
   */
  public AbstractTrackedEntityAssert hasModifiedOn(Date modifiedOn) {
    // check that actual AbstractTrackedEntity we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String errorMessage = "\nExpected modifiedOn of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

    // null safe check
    Date actualModifiedOn = actual.getModifiedOn();
    if (!org.assertj.core.util.Objects.areEqual(actualModifiedOn, modifiedOn)) {
      failWithMessage(errorMessage, actual, modifiedOn, actualModifiedOn);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual AbstractTrackedEntity's modifier is equal to the given one.
   * @param modifier the given modifier to compare the actual AbstractTrackedEntity's modifier to.
   * @return this assertion object.
   * @throws AssertionError - if the actual AbstractTrackedEntity's modifier is not equal to the given one.
   */
  public AbstractTrackedEntityAssert hasModifier(User modifier) {
    // check that actual AbstractTrackedEntity we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String errorMessage = "\nExpected modifier of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

    // null safe check
    User actualModifier = actual.getModifier();
    if (!org.assertj.core.util.Objects.areEqual(actualModifier, modifier)) {
      failWithMessage(errorMessage, actual, modifier, actualModifier);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual AbstractTrackedEntity's rev is equal to the given one.
   * @param rev the given rev to compare the actual AbstractTrackedEntity's rev to.
   * @return this assertion object.
   * @throws AssertionError - if the actual AbstractTrackedEntity's rev is not equal to the given one.
   */
  public AbstractTrackedEntityAssert hasRev(long rev) {
    // check that actual AbstractTrackedEntity we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String errorMessage = "\nExpected rev of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

    // check
    long actualRev = actual.getRev();
    if (actualRev != rev) {
      failWithMessage(errorMessage, actual, rev, actualRev);
    }

    // return the current assertion for method chaining
    return this;
  }

}
