package elaborate.editor.model;

import org.assertj.core.api.AbstractAssert;
// Assertions is needed if an assertion for Iterable is generated
import org.assertj.core.api.Assertions;
import elaborate.editor.model.orm.Project;
import elaborate.editor.model.orm.User;
import java.util.Date;


/**
 * {@link AbstractProjectEntity} specific assertions - Generated by CustomAssertionGenerator.
 */
public class AbstractProjectEntityAssert extends AbstractAssert<AbstractProjectEntityAssert, AbstractProjectEntity> {

  /**
   * Creates a new </code>{@link AbstractProjectEntityAssert}</code> to make assertions on actual AbstractProjectEntity.
   * @param actual the AbstractProjectEntity we want to make assertions on.
   */
  public AbstractProjectEntityAssert(AbstractProjectEntity actual) {
    super(actual, AbstractProjectEntityAssert.class);
  }

  /**
   * An entry point for AbstractProjectEntityAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one's can write directly : <code>assertThat(myAbstractProjectEntity)</code> and get specific assertion with code completion.
   * @param actual the AbstractProjectEntity we want to make assertions on.
   * @return a new </code>{@link AbstractProjectEntityAssert}</code>
   */
  public static AbstractProjectEntityAssert assertThat(AbstractProjectEntity actual) {
    return new AbstractProjectEntityAssert(actual);
  }

  /**
   * Verifies that the actual AbstractProjectEntity's createdOn is equal to the given one.
   * @param createdOn the given createdOn to compare the actual AbstractProjectEntity's createdOn to.
   * @return this assertion object.
   * @throws AssertionError - if the actual AbstractProjectEntity's createdOn is not equal to the given one.
   */
  public AbstractProjectEntityAssert hasCreatedOn(Date createdOn) {
    // check that actual AbstractProjectEntity we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String errorMessage = "\nExpected createdOn of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // null safe check
    Date actualCreatedOn = actual.getCreatedOn();
    if (!org.assertj.core.util.Objects.areEqual(actualCreatedOn, createdOn)) {
      failWithMessage(errorMessage, actual, createdOn, actualCreatedOn);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual AbstractProjectEntity's creator is equal to the given one.
   * @param creator the given creator to compare the actual AbstractProjectEntity's creator to.
   * @return this assertion object.
   * @throws AssertionError - if the actual AbstractProjectEntity's creator is not equal to the given one.
   */
  public AbstractProjectEntityAssert hasCreator(User creator) {
    // check that actual AbstractProjectEntity we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String errorMessage = "\nExpected creator of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // null safe check
    User actualCreator = actual.getCreator();
    if (!org.assertj.core.util.Objects.areEqual(actualCreator, creator)) {
      failWithMessage(errorMessage, actual, creator, actualCreator);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual AbstractProjectEntity's id is equal to the given one.
   * @param id the given id to compare the actual AbstractProjectEntity's id to.
   * @return this assertion object.
   * @throws AssertionError - if the actual AbstractProjectEntity's id is not equal to the given one.
   */
  public AbstractProjectEntityAssert hasId(long id) {
    // check that actual AbstractProjectEntity we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String errorMessage = "\nExpected id of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // check
    long actualId = actual.getId();
    if (actualId != id) {
      failWithMessage(errorMessage, actual, id, actualId);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual AbstractProjectEntity's modifiedOn is equal to the given one.
   * @param modifiedOn the given modifiedOn to compare the actual AbstractProjectEntity's modifiedOn to.
   * @return this assertion object.
   * @throws AssertionError - if the actual AbstractProjectEntity's modifiedOn is not equal to the given one.
   */
  public AbstractProjectEntityAssert hasModifiedOn(Date modifiedOn) {
    // check that actual AbstractProjectEntity we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String errorMessage = "\nExpected modifiedOn of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // null safe check
    Date actualModifiedOn = actual.getModifiedOn();
    if (!org.assertj.core.util.Objects.areEqual(actualModifiedOn, modifiedOn)) {
      failWithMessage(errorMessage, actual, modifiedOn, actualModifiedOn);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual AbstractProjectEntity's modifier is equal to the given one.
   * @param modifier the given modifier to compare the actual AbstractProjectEntity's modifier to.
   * @return this assertion object.
   * @throws AssertionError - if the actual AbstractProjectEntity's modifier is not equal to the given one.
   */
  public AbstractProjectEntityAssert hasModifier(User modifier) {
    // check that actual AbstractProjectEntity we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String errorMessage = "\nExpected modifier of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // null safe check
    User actualModifier = actual.getModifier();
    if (!org.assertj.core.util.Objects.areEqual(actualModifier, modifier)) {
      failWithMessage(errorMessage, actual, modifier, actualModifier);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual AbstractProjectEntity's project is equal to the given one.
   * @param project the given project to compare the actual AbstractProjectEntity's project to.
   * @return this assertion object.
   * @throws AssertionError - if the actual AbstractProjectEntity's project is not equal to the given one.
   */
  public AbstractProjectEntityAssert hasProject(Project project) {
    // check that actual AbstractProjectEntity we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String errorMessage = "\nExpected project of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // null safe check
    Project actualProject = actual.getProject();
    if (!org.assertj.core.util.Objects.areEqual(actualProject, project)) {
      failWithMessage(errorMessage, actual, project, actualProject);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual AbstractProjectEntity's rev is equal to the given one.
   * @param rev the given rev to compare the actual AbstractProjectEntity's rev to.
   * @return this assertion object.
   * @throws AssertionError - if the actual AbstractProjectEntity's rev is not equal to the given one.
   */
  public AbstractProjectEntityAssert hasRev(long rev) {
    // check that actual AbstractProjectEntity we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String errorMessage = "\nExpected rev of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // check
    long actualRev = actual.getRev();
    if (actualRev != rev) {
      failWithMessage(errorMessage, actual, rev, actualRev);
    }

    // return the current assertion for method chaining
    return this;
  }

}
