package elaborate.editor.model;

import org.assertj.core.api.AbstractAssert;
// Assertions is needed if an assertion for Iterable is generated
import org.assertj.core.api.Assertions;


/**
 * {@link AbstractStoredEntity} specific assertions - Generated by CustomAssertionGenerator.
 */
public class AbstractStoredEntityAssert extends AbstractAssert<AbstractStoredEntityAssert, AbstractStoredEntity> {

  /**
   * Creates a new </code>{@link AbstractStoredEntityAssert}</code> to make assertions on actual AbstractStoredEntity.
   * @param actual the AbstractStoredEntity we want to make assertions on.
   */
  public AbstractStoredEntityAssert(AbstractStoredEntity actual) {
    super(actual, AbstractStoredEntityAssert.class);
  }

  /**
   * An entry point for AbstractStoredEntityAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one's can write directly : <code>assertThat(myAbstractStoredEntity)</code> and get specific assertion with code completion.
   * @param actual the AbstractStoredEntity we want to make assertions on.
   * @return a new </code>{@link AbstractStoredEntityAssert}</code>
   */
  public static AbstractStoredEntityAssert assertThat(AbstractStoredEntity actual) {
    return new AbstractStoredEntityAssert(actual);
  }

  /**
   * Verifies that the actual AbstractStoredEntity's id is equal to the given one.
   * @param id the given id to compare the actual AbstractStoredEntity's id to.
   * @return this assertion object.
   * @throws AssertionError - if the actual AbstractStoredEntity's id is not equal to the given one.
   */
  public AbstractStoredEntityAssert hasId(long id) {
    // check that actual AbstractStoredEntity we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String errorMessage = "\nExpected id of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // check
    long actualId = actual.getId();
    if (actualId != id) {
      failWithMessage(errorMessage, actual, id, actualId);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual AbstractStoredEntity's rev is equal to the given one.
   * @param rev the given rev to compare the actual AbstractStoredEntity's rev to.
   * @return this assertion object.
   * @throws AssertionError - if the actual AbstractStoredEntity's rev is not equal to the given one.
   */
  public AbstractStoredEntityAssert hasRev(long rev) {
    // check that actual AbstractStoredEntity we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String errorMessage = "\nExpected rev of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // check
    long actualRev = actual.getRev();
    if (actualRev != rev) {
      failWithMessage(errorMessage, actual, rev, actualRev);
    }

    // return the current assertion for method chaining
    return this;
  }

}
