package elaborate.editor.model;

import org.assertj.core.api.AbstractAssert;

// Assertions is needed if an assertion for Iterable is generated

/**
 * {@link Action} specific assertions - Generated by CustomAssertionGenerator.
 */
public class ActionAssert extends AbstractAssert<ActionAssert, Action> {

  /**
   * Creates a new </code>{@link ActionAssert}</code> to make assertions on actual Action.
   * @param actual the Action we want to make assertions on.
   */
  public ActionAssert(Action actual) {
    super(actual, ActionAssert.class);
  }

  /**
   * An entry point for ActionAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one's can write directly : <code>assertThat(myAction)</code> and get specific assertion with code completion.
   * @param actual the Action we want to make assertions on.
   * @return a new </code>{@link ActionAssert}</code>
   */
  public static ActionAssert assertThat(Action actual) {
    return new ActionAssert(actual);
  }

  /**
   * Verifies that the actual Action's declaringClass is equal to the given one.
   * @param declaringClass the given declaringClass to compare the actual Action's declaringClass to.
   * @return this assertion object.
   * @throws AssertionError - if the actual Action's declaringClass is not equal to the given one.
   */
  public ActionAssert hasDeclaringClass(Class declaringClass) {
    // check that actual Action we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String errorMessage = "\nExpected declaringClass of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

    // null safe check
    Class actualDeclaringClass = actual.getDeclaringClass();
    if (!org.assertj.core.util.Objects.areEqual(actualDeclaringClass, declaringClass)) {
      failWithMessage(errorMessage, actual, declaringClass, actualDeclaringClass);
    }

    // return the current assertion for method chaining
    return this;
  }

}
