package elaborate.editor.model;

import org.assertj.core.api.AbstractAssert;
// Assertions is needed if an assertion for Iterable is generated
import org.assertj.core.api.Assertions;


/**
 * {@link Views.Extended} specific assertions - Generated by CustomAssertionGenerator.
 */
public class ExtendedAssert extends AbstractAssert<ExtendedAssert, Views.Extended> {

  /**
   * Creates a new </code>{@link ExtendedAssert}</code> to make assertions on actual Views.Extended.
   * @param actual the Views.Extended we want to make assertions on.
   */
  public ExtendedAssert(Views.Extended actual) {
    super(actual, ExtendedAssert.class);
  }

  /**
   * An entry point for ExtendedAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one's can write directly : <code>assertThat(myViews.Extended)</code> and get specific assertion with code completion.
   * @param actual the Views.Extended we want to make assertions on.
   * @return a new </code>{@link ExtendedAssert}</code>
   */
  public static ExtendedAssert assertThat(Views.Extended actual) {
    return new ExtendedAssert(actual);
  }

}
