package elaborate.editor.model;

import org.assertj.core.api.AbstractAssert;

// Assertions is needed if an assertion for Iterable is generated

/**
 * {@link Views.IdOnly} specific assertions - Generated by CustomAssertionGenerator.
 */
public class IdOnlyAssert extends AbstractAssert<IdOnlyAssert, Views.IdOnly> {

  /**
   * Creates a new </code>{@link IdOnlyAssert}</code> to make assertions on actual Views.IdOnly.
   * @param actual the Views.IdOnly we want to make assertions on.
   */
  public IdOnlyAssert(Views.IdOnly actual) {
    super(actual, IdOnlyAssert.class);
  }

  /**
   * An entry point for IdOnlyAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one's can write directly : <code>assertThat(myViews.IdOnly)</code> and get specific assertion with code completion.
   * @param actual the Views.IdOnly we want to make assertions on.
   * @return a new </code>{@link IdOnlyAssert}</code>
   */
  public static IdOnlyAssert assertThat(Views.IdOnly actual) {
    return new IdOnlyAssert(actual);
  }

}
