package elaborate.editor.model;

import org.assertj.core.api.AbstractAssert;

// Assertions is needed if an assertion for Iterable is generated

/**
 * {@link Permissions} specific assertions - Generated by CustomAssertionGenerator.
 */
public class PermissionsAssert extends AbstractAssert<PermissionsAssert, Permissions> {

  /**
   * Creates a new </code>{@link PermissionsAssert}</code> to make assertions on actual Permissions.
   * @param actual the Permissions we want to make assertions on.
   */
  public PermissionsAssert(Permissions actual) {
    super(actual, PermissionsAssert.class);
  }

  /**
   * An entry point for PermissionsAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one's can write directly : <code>assertThat(myPermissions)</code> and get specific assertion with code completion.
   * @param actual the Permissions we want to make assertions on.
   * @return a new </code>{@link PermissionsAssert}</code>
   */
  public static PermissionsAssert assertThat(Permissions actual) {
    return new PermissionsAssert(actual);
  }

}
