package elaborate.editor.model;

import org.assertj.core.api.AbstractAssert;

// Assertions is needed if an assertion for Iterable is generated

/**
 * {@link Permission} specific assertions - Generated by CustomAssertionGenerator.
 */
public class PermissionAssert extends AbstractAssert<PermissionAssert, Permission> {

  /**
   * Creates a new </code>{@link PermissionAssert}</code> to make assertions on actual Permission.
   * @param actual the Permission we want to make assertions on.
   */
  public PermissionAssert(Permission actual) {
    super(actual, PermissionAssert.class);
  }

  /**
   * An entry point for PermissionAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one's can write directly : <code>assertThat(myPermission)</code> and get specific assertion with code completion.
   * @param actual the Permission we want to make assertions on.
   * @return a new </code>{@link PermissionAssert}</code>
   */
  public static PermissionAssert assertThat(Permission actual) {
    return new PermissionAssert(actual);
  }

}
