package elaborate.editor.model;

import org.assertj.core.api.AbstractAssert;

// Assertions is needed if an assertion for Iterable is generated

/**
 * {@link ProjectTypes} specific assertions - Generated by CustomAssertionGenerator.
 */
public class ProjectTypesAssert extends AbstractAssert<ProjectTypesAssert, ProjectTypes> {

  /**
   * Creates a new </code>{@link ProjectTypesAssert}</code> to make assertions on actual ProjectTypes.
   * @param actual the ProjectTypes we want to make assertions on.
   */
  public ProjectTypesAssert(ProjectTypes actual) {
    super(actual, ProjectTypesAssert.class);
  }

  /**
   * An entry point for ProjectTypesAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one's can write directly : <code>assertThat(myProjectTypes)</code> and get specific assertion with code completion.
   * @param actual the ProjectTypes we want to make assertions on.
   * @return a new </code>{@link ProjectTypesAssert}</code>
   */
  public static ProjectTypesAssert assertThat(ProjectTypes actual) {
    return new ProjectTypesAssert(actual);
  }

}
