package elaborate.editor.model;

import org.assertj.core.api.AbstractAssert;
// Assertions is needed if an assertion for Iterable is generated
import org.assertj.core.api.Assertions;


/**
 * {@link ProjectMetadataFields} specific assertions - Generated by CustomAssertionGenerator.
 */
public class ProjectMetadataFieldsAssert extends AbstractAssert<ProjectMetadataFieldsAssert, ProjectMetadataFields> {

  /**
   * Creates a new </code>{@link ProjectMetadataFieldsAssert}</code> to make assertions on actual ProjectMetadataFields.
   * @param actual the ProjectMetadataFields we want to make assertions on.
   */
  public ProjectMetadataFieldsAssert(ProjectMetadataFields actual) {
    super(actual, ProjectMetadataFieldsAssert.class);
  }

  /**
   * An entry point for ProjectMetadataFieldsAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one's can write directly : <code>assertThat(myProjectMetadataFields)</code> and get specific assertion with code completion.
   * @param actual the ProjectMetadataFields we want to make assertions on.
   * @return a new </code>{@link ProjectMetadataFieldsAssert}</code>
   */
  public static ProjectMetadataFieldsAssert assertThat(ProjectMetadataFields actual) {
    return new ProjectMetadataFieldsAssert(actual);
  }

}
