package elaborate.editor.model;

import org.assertj.core.api.AbstractAssert;
// Assertions is needed if an assertion for Iterable is generated
import org.assertj.core.api.Assertions;


/**
 * {@link SessionService} specific assertions - Generated by CustomAssertionGenerator.
 */
public class SessionServiceAssert extends AbstractAssert<SessionServiceAssert, SessionService> {

  /**
   * Creates a new </code>{@link SessionServiceAssert}</code> to make assertions on actual SessionService.
   * @param actual the SessionService we want to make assertions on.
   */
  public SessionServiceAssert(SessionService actual) {
    super(actual, SessionServiceAssert.class);
  }

  /**
   * An entry point for SessionServiceAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one's can write directly : <code>assertThat(mySessionService)</code> and get specific assertion with code completion.
   * @param actual the SessionService we want to make assertions on.
   * @return a new </code>{@link SessionServiceAssert}</code>
   */
  public static SessionServiceAssert assertThat(SessionService actual) {
    return new SessionServiceAssert(actual);
  }

}
