package elaborate.editor.model.orm;

import org.assertj.core.api.AbstractAssert;

// Assertions is needed if an assertion for Iterable is generated

/**
 * {@link Transcription.BodyTags} specific assertions - Generated by CustomAssertionGenerator.
 */
public class BodyTagsAssert extends AbstractAssert<BodyTagsAssert, Transcription.BodyTags> {

  /**
   * Creates a new </code>{@link BodyTagsAssert}</code> to make assertions on actual Transcription.BodyTags.
   * @param actual the Transcription.BodyTags we want to make assertions on.
   */
  public BodyTagsAssert(Transcription.BodyTags actual) {
    super(actual, BodyTagsAssert.class);
  }

  /**
   * An entry point for BodyTagsAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one's can write directly : <code>assertThat(myTranscription.BodyTags)</code> and get specific assertion with code completion.
   * @param actual the Transcription.BodyTags we want to make assertions on.
   * @return a new </code>{@link BodyTagsAssert}</code>
   */
  public static BodyTagsAssert assertThat(Transcription.BodyTags actual) {
    return new BodyTagsAssert(actual);
  }

}
