package elaborate.editor.model.orm;

import java.util.Date;

import org.assertj.core.api.AbstractAssert;

// Assertions is needed if an assertion for Iterable is generated

/**
 * {@link ProjectEntryMetadataItem} specific assertions - Generated by CustomAssertionGenerator.
 */
public class ProjectEntryMetadataItemAssert extends AbstractAssert<ProjectEntryMetadataItemAssert, ProjectEntryMetadataItem> {

  /**
   * Creates a new </code>{@link ProjectEntryMetadataItemAssert}</code> to make assertions on actual ProjectEntryMetadataItem.
   * @param actual the ProjectEntryMetadataItem we want to make assertions on.
   */
  public ProjectEntryMetadataItemAssert(ProjectEntryMetadataItem actual) {
    super(actual, ProjectEntryMetadataItemAssert.class);
  }

  /**
   * An entry point for ProjectEntryMetadataItemAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one's can write directly : <code>assertThat(myProjectEntryMetadataItem)</code> and get specific assertion with code completion.
   * @param actual the ProjectEntryMetadataItem we want to make assertions on.
   * @return a new </code>{@link ProjectEntryMetadataItemAssert}</code>
   */
  public static ProjectEntryMetadataItemAssert assertThat(ProjectEntryMetadataItem actual) {
    return new ProjectEntryMetadataItemAssert(actual);
  }

  /**
   * Verifies that the actual ProjectEntryMetadataItem's createdOn is equal to the given one.
   * @param createdOn the given createdOn to compare the actual ProjectEntryMetadataItem's createdOn to.
   * @return this assertion object.
   * @throws AssertionError - if the actual ProjectEntryMetadataItem's createdOn is not equal to the given one.
   */
  public ProjectEntryMetadataItemAssert hasCreatedOn(Date createdOn) {
    // check that actual ProjectEntryMetadataItem we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String errorMessage = "\nExpected createdOn of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

    // null safe check
    Date actualCreatedOn = actual.getCreatedOn();
    if (!org.assertj.core.util.Objects.areEqual(actualCreatedOn, createdOn)) {
      failWithMessage(errorMessage, actual, createdOn, actualCreatedOn);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual ProjectEntryMetadataItem's creator is equal to the given one.
   * @param creator the given creator to compare the actual ProjectEntryMetadataItem's creator to.
   * @return this assertion object.
   * @throws AssertionError - if the actual ProjectEntryMetadataItem's creator is not equal to the given one.
   */
  public ProjectEntryMetadataItemAssert hasCreator(User creator) {
    // check that actual ProjectEntryMetadataItem we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String errorMessage = "\nExpected creator of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

    // null safe check
    User actualCreator = actual.getCreator();
    if (!org.assertj.core.util.Objects.areEqual(actualCreator, creator)) {
      failWithMessage(errorMessage, actual, creator, actualCreator);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual ProjectEntryMetadataItem's data is equal to the given one.
   * @param data the given data to compare the actual ProjectEntryMetadataItem's data to.
   * @return this assertion object.
   * @throws AssertionError - if the actual ProjectEntryMetadataItem's data is not equal to the given one.
   */
  public ProjectEntryMetadataItemAssert hasData(String data) {
    // check that actual ProjectEntryMetadataItem we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String errorMessage = "\nExpected data of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

    // null safe check
    String actualData = actual.getData();
    if (!org.assertj.core.util.Objects.areEqual(actualData, data)) {
      failWithMessage(errorMessage, actual, data, actualData);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual ProjectEntryMetadataItem's facetName is equal to the given one.
   * @param facetName the given facetName to compare the actual ProjectEntryMetadataItem's facetName to.
   * @return this assertion object.
   * @throws AssertionError - if the actual ProjectEntryMetadataItem's facetName is not equal to the given one.
   */
  public ProjectEntryMetadataItemAssert hasFacetName(String facetName) {
    // check that actual ProjectEntryMetadataItem we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String errorMessage = "\nExpected facetName of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

    // null safe check
    String actualFacetName = actual.getFacetName();
    if (!org.assertj.core.util.Objects.areEqual(actualFacetName, facetName)) {
      failWithMessage(errorMessage, actual, facetName, actualFacetName);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual ProjectEntryMetadataItem's field is equal to the given one.
   * @param field the given field to compare the actual ProjectEntryMetadataItem's field to.
   * @return this assertion object.
   * @throws AssertionError - if the actual ProjectEntryMetadataItem's field is not equal to the given one.
   */
  public ProjectEntryMetadataItemAssert hasField(String field) {
    // check that actual ProjectEntryMetadataItem we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String errorMessage = "\nExpected field of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

    // null safe check
    String actualField = actual.getField();
    if (!org.assertj.core.util.Objects.areEqual(actualField, field)) {
      failWithMessage(errorMessage, actual, field, actualField);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual ProjectEntryMetadataItem's id is equal to the given one.
   * @param id the given id to compare the actual ProjectEntryMetadataItem's id to.
   * @return this assertion object.
   * @throws AssertionError - if the actual ProjectEntryMetadataItem's id is not equal to the given one.
   */
  public ProjectEntryMetadataItemAssert hasId(long id) {
    // check that actual ProjectEntryMetadataItem we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String errorMessage = "\nExpected id of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

    // check
    long actualId = actual.getId();
    if (actualId != id) {
      failWithMessage(errorMessage, actual, id, actualId);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual ProjectEntryMetadataItem's modifiedOn is equal to the given one.
   * @param modifiedOn the given modifiedOn to compare the actual ProjectEntryMetadataItem's modifiedOn to.
   * @return this assertion object.
   * @throws AssertionError - if the actual ProjectEntryMetadataItem's modifiedOn is not equal to the given one.
   */
  public ProjectEntryMetadataItemAssert hasModifiedOn(Date modifiedOn) {
    // check that actual ProjectEntryMetadataItem we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String errorMessage = "\nExpected modifiedOn of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

    // null safe check
    Date actualModifiedOn = actual.getModifiedOn();
    if (!org.assertj.core.util.Objects.areEqual(actualModifiedOn, modifiedOn)) {
      failWithMessage(errorMessage, actual, modifiedOn, actualModifiedOn);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual ProjectEntryMetadataItem's modifier is equal to the given one.
   * @param modifier the given modifier to compare the actual ProjectEntryMetadataItem's modifier to.
   * @return this assertion object.
   * @throws AssertionError - if the actual ProjectEntryMetadataItem's modifier is not equal to the given one.
   */
  public ProjectEntryMetadataItemAssert hasModifier(User modifier) {
    // check that actual ProjectEntryMetadataItem we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String errorMessage = "\nExpected modifier of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

    // null safe check
    User actualModifier = actual.getModifier();
    if (!org.assertj.core.util.Objects.areEqual(actualModifier, modifier)) {
      failWithMessage(errorMessage, actual, modifier, actualModifier);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual ProjectEntryMetadataItem's projectEntry is equal to the given one.
   * @param projectEntry the given projectEntry to compare the actual ProjectEntryMetadataItem's projectEntry to.
   * @return this assertion object.
   * @throws AssertionError - if the actual ProjectEntryMetadataItem's projectEntry is not equal to the given one.
   */
  public ProjectEntryMetadataItemAssert hasProjectEntry(ProjectEntry projectEntry) {
    // check that actual ProjectEntryMetadataItem we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String errorMessage = "\nExpected projectEntry of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

    // null safe check
    ProjectEntry actualProjectEntry = actual.getProjectEntry();
    if (!org.assertj.core.util.Objects.areEqual(actualProjectEntry, projectEntry)) {
      failWithMessage(errorMessage, actual, projectEntry, actualProjectEntry);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual ProjectEntryMetadataItem's rev is equal to the given one.
   * @param rev the given rev to compare the actual ProjectEntryMetadataItem's rev to.
   * @return this assertion object.
   * @throws AssertionError - if the actual ProjectEntryMetadataItem's rev is not equal to the given one.
   */
  public ProjectEntryMetadataItemAssert hasRev(long rev) {
    // check that actual ProjectEntryMetadataItem we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String errorMessage = "\nExpected rev of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

    // check
    long actualRev = actual.getRev();
    if (actualRev != rev) {
      failWithMessage(errorMessage, actual, rev, actualRev);
    }

    // return the current assertion for method chaining
    return this;
  }

}
